import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SelectComponent from '@/components/SelectComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { lang }
}: {
  children: React.ReactNode,
  params: { lang: string }
}) {
  // console.log(params)
  return (
    <html lang={lang}>
      <body className={inter.className}>
        {<SelectComponent />}
        {children}
      </body>
    </html>
  )
}
